language: php

php:
  - 5.4

sudo: false

install: 
    - composer self-update
    - travis_retry composer install --no-interaction --prefer-source   

script: vendor/bin/phpunit-randomizer --coverage-text --order rand 
